gui_publish_rate: 5
kld_err: 0.01
kld_z: 0.99
laser_lambda_short: 0.1
laser_likelihood_max_dist: 2.0
laser_max_beams: 50
laser_model_type: likelihood_field
laser_sigma_hit: 0.2
laser_z_hit: 0.5
laser_z_max: 0.05
laser_z_rand: 0.5
laser_z_short: 0.05
max_particles: 5000
min_particles: 500
odom_alpha1: 0.02
odom_alpha2: 0.02
odom_alpha3: 0.02
odom_alpha4: 0.02
odom_alpha5: 0.02
odom_frame_id: odom
odom_model_type: diff-corrected
recovery_alpha_fast: 0.0
recovery_alpha_slow: 0.0
resample_interval: 2
transform_tolerance: 0.3
update_min_a: 0.05
update_min_d: 0.05
